# Generated by Django 5.1.2 on 2024-10-31 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                blank=True,
                help_text="Укажите имя",
                max_length=200,
                null=True,
                verbose_name="имя",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                blank=True,
                help_text="Укажите фамилию",
                max_length=200,
                null=True,
                verbose_name="фамилия",
            ),
        ),
    ]
